language: nodejs
nodejs:
  - "0.10"
before_script:
  - npm install --save --save-exact grunt grunt-cli
install: true
script:
  - npm install
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
