language: nodejs
nodejs:
  - "0.10"
before_script:
  - npm install -g grunt-cli bower
install: true
script:
  - npm install
  - bower install
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
