language: nodejs
nodejs:
  - "0.10"
install: true
before_script:
  - npm install --save --save-exact bower
script:
  - npm install
  - bower install
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
